version: "3"

services:
  biotechnica:
    build: .
    ports: 
      - "2077:2077"
    volumes:
      - .:/app
    devices:
      - "/dev/video2:/dev/video2"
    privileged: true  # Required for camera access
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "2077", "--reload"]