version: "3"

services:
  biotechnica:
    build: .
    ports: 
      - "2076:2076"
    volumes:
      - .:/app
      - ./CapturedImages:/app/CapturedImages
      - ./CalibrationImages:/app/CalibrationImages
      - ./UndistortedImages:/app/UndistortedImages
      - ./camera_calibration_params:/app/camera_calibration_params
      - ./SplitDataset:/app/SplitDataset
    devices:
      - "/dev/video2:/dev/video2"
    privileged: true
    environment:
      - PYTHONPATH=/app
    command: ["sh", "-c", "if [ \"$UVICORN_RELOAD\" = \"true\" ]; then uvicorn api_server:app --host 0.0.0.0 --port 2076 --reload; else python api_server.py; fi"]

  kiroshi:
    image: node:18
    working_dir: /app
    ports:
      - "2077:2077"
    volumes:
      - ./pe_medicinerecognision:/app
      - /app/node_modules
    environment:
       - NODE_ENV=development
       - CHOKIDAR_USEPOLLING=true
    command: ["sh", "-c", "npm install && npm run dev"]
    depends_on:
      - biotechnica
