from pathlib import Path

class AppConfig:
    CONFIG_FILE = "Data/JSON/camera_params.json"
    CALI_CONFIG_FILE = "Data/JSON/camera_calibration_params.json"
    CAPTURED_IMAGES_DIR = "Data/CapturedImages"
    CALIBRATION_IMAGES_DIR = "Data/CalibrationImages"
    UNDISTORTED_IMAGES_DIR = "Data/UndistortedImages"
    PILLS_DATA_FILE = "Data/JSON/Pills.json"
    LOG = "Logs"
    DATASET_IMAGES = "Data/Dataset/images"
    DATASET_LABELS = "Data/Dataset/segmentation_labels"
    DATASET_MASKS = "Data/Dataset/mask_images"
    SPLIT_DATASET = "Data/Split"
    SPLIT_TRAIN_IMAGES = "Data/Split/train/images"
    SPLIT_TRAIN_LABELS = "Data/Split/train/labels"
    SPLIT_TRAIN_MASKS = "Data/Split/train/masks"
    SPLIT_VAL_IMAGES = "Data/Split/val/images"
    SPLIT_VAL_LABELS = "Data/Split/val/labels"
    SPLIT_VAL_MASKS = "Data/Split/val/masks"
    AUG_IMAGES = "Data/Augmentation/images"
    AUG_MASKS = "Data/Augmentation/masks"
    AUG_ANN = "Data/Augmentation/annotation"
    BACKGROUND_IMAGES = "Data/BackgroundImages"